### ISSUE TITLE
Модуль masonry галереи в статьях

### ISSUE THREAD

**Issue by GordonBreazz** [tjournal-pl/TJournal.ru#1]
В каком модуле можно посмотреть на реализацию masonry галереи которую используют в статьях сайты Комитета ?

**Comment by aleksy91** [comment]
Версии модулей уже устаревшие, это версия от августа 2018 года. Если нужна версия от 20 июня 2020 года, то пишите на почту. За 2 года Комитет сильно переписал код, но все также используются модули, что и в 2018 году.
